### ISSUE TITLE
Persistence and timestamps

### ISSUE THREAD

**Issue by djesic** [Wolkabout/WolkGateway#33]
In cases where modules send data without timestamps to the gateway, but the gateway is not connected to the platform at the moment, the data is placed into storage. Is this data then assigned a timestamp when being placed into storage in order to prevent it from being treated as "live" when connection is restored and stored data is published?

**Comment by milanzlicic** [comment]
No, gw does not modify message content which rtc is a part of

**Comment by djesic** [comment]
Marking resolved as this will be done in Module SDKs then instead.
